"""
data.py — CZN game data
========================
All static game data: character builds, set info, stat weights, roll ranges.
Edit this file to update characters or add new sets.
"""

# ── Roll ranges per single upgrade (Legendary, source: Prydwen) ──────────────
# Each value is (min, max) for one roll.
# At +1 the fragment has base values (= 1 roll). Each upgrade adds 1 more roll.
# Legendary fragments: 4 upgrade rolls total (+1 to +5).
ROLL_RANGES = {
    "ATK":          (5.0,  8.0),
    "DEF":          (3.0,  5.0),
    "HP":           (10.0, 12.0),
    "ATK%":         (0.8,  1.3),
    "DEF%":         (0.8,  1.3),
    "HP%":          (0.8,  1.3),
    "Crit Rate%":   (1.2,  2.0),
    "Crit DMG%":    (2.4,  4.0),
    "EGO Recovery": (2.0,  5.0),
    "DoT%":         (2.7,  3.4),
    "Extra DMG%":   (2.7,  3.4),
}

# Dream roll maximum (base + 4 rolls all on same stat at max, source: Prydwen)
DREAM_MAX = {
    "ATK":          40,
    "DEF":          25,
    "HP":           60,
    "ATK%":         6.5,
    "DEF%":         6.5,
    "HP%":          6.5,
    "Crit Rate%":   10.0,
    "Crit DMG%":    20.0,
    "EGO Recovery": 25,
    "DoT%":         17.0,
    "Extra DMG%":   17.0,
}

# ── Slot system ───────────────────────────────────────────────────────────────
# Shock/Suppression/Denial have fixed main stats; Ideal/Desire/Imagination are variable
FIXED_MAIN = {"shock": "ATK", "suppression": "DEF", "denial": "HP"}

SLOT_NAMES = {
    "shock":"shock",       "i":"shock",       "1":"shock",
    "suppression":"suppression", "ii":"suppression", "2":"suppression",
    "denial":"denial",     "iii":"denial",    "3":"denial",
    "ideal":"ideal",       "iv":"ideal",      "4":"ideal",
    "desire":"desire",     "v":"desire",      "5":"desire",
    "imagination":"imagination", "vi":"imagination", "6":"imagination",
}

SLOT_DISPLAY = {
    "shock":        "I · Shock",
    "suppression":  "II · Suppression",
    "denial":       "III · Denial",
    "ideal":        "IV · Ideal",
    "desire":       "V · Desire",
    "imagination":  "VI · Imagination",
}

# Variant slot names used in fragment titles (e.g. "Black Wing Longing" = Ideal slot)
TITLE_SLOT_MAP = {
    "shock":        "shock",
    "suppression":  "suppression",
    "denial":       "denial",
    "ideal":        "ideal",
    "desire":       "desire",
    "imagination":  "imagination",
    "longing":      "ideal",
    "anomaly":      "ideal",
    "resolution":   "desire",
    "fragment":     "imagination",
    "trace":        "imagination",
}

# Attribute DMG stats — always main stat, never sub-stat
ATTR_DMG_STATS = {
    "Order DMG%", "Void DMG%", "Instinct DMG%", "Chaos DMG%",
    "Justice DMG%", "Passion DMG%", "Attribute DMG%",
}

# ── Stat weight templates ─────────────────────────────────────────────────────
# 0.0 = useless, 0.5 = ok, 0.75 = good, 1.0 = best in slot
CRIT_DPS = {
    "Crit Rate%":1.0, "Crit DMG%":1.0, "ATK":0.75, "ATK%":0.5,
    "DEF":0.0, "DEF%":0.0, "HP":0.0, "HP%":0.0, "EGO Recovery":0.0,
    "DoT%":0.0, "Extra DMG%":0.0,
}
NINE_W = {
    "Crit Rate%":1.0, "Crit DMG%":1.0, "DEF":0.75, "DEF%":0.5,
    "ATK":0.25, "ATK%":0.1, "HP":0.0, "HP%":0.0, "EGO Recovery":0.0,
    "DoT%":0.0, "Extra DMG%":0.0,
}
TIPHERA_W = {
    "DEF":1.0, "DEF%":0.9, "Crit Rate%":0.6, "Crit DMG%":0.6,
    "HP":0.1, "HP%":0.1, "ATK":0.0, "ATK%":0.0, "EGO Recovery":0.1,
    "DoT%":0.0, "Extra DMG%":0.0,
}
KHALIPE_W = {
    "Crit Rate%":1.0, "Crit DMG%":0.9, "DEF":0.9, "DEF%":0.7,
    "EGO Recovery":0.4, "ATK":0.1, "ATK%":0.1, "HP":0.0, "HP%":0.0,
    "DoT%":0.0, "Extra DMG%":0.0,
}
DEF_SUP_W = {
    "DEF":1.0, "DEF%":0.9, "HP":0.6, "HP%":0.5, "EGO Recovery":0.5,
    "Crit Rate%":0.0, "Crit DMG%":0.0, "ATK":0.0, "ATK%":0.0,
    "DoT%":0.0, "Extra DMG%":0.0,
}
HP_SUP_W = {
    "HP":1.0, "HP%":0.9, "DEF":0.8, "DEF%":0.7, "EGO Recovery":0.5,
    "Crit Rate%":0.0, "Crit DMG%":0.0, "ATK":0.0, "ATK%":0.0,
    "DoT%":0.0, "Extra DMG%":0.0,
}

# ── Characters (source: Prydwen.gg) ──────────────────────────────────────────
# sets:      Memory Fragment sets this character uses
# weights:   Sub-stat priority weights (0.0-1.0)
# good_main: Acceptable main stats per variable slot (str or list)
# goal:      Build goal / stat target
CHARS = {
    "Nine":     {"sets":["Line of Justice","Beast's Yearning","Conqueror's Aspect",
                         "Executioner's Tool","Blackwing","Cursed Corpse","Bullet of Order"],
                 "weights":NINE_W,
                 "good_main":{"desire":"Order DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"350 DEF · Potential 7"},
    "Veronica": {"sets":["Line of Justice","Beast's Yearning","Executioner's Tool","Blackwing"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Order DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Crit DPS"},
    "Beryl":    {"sets":["Line of Justice","Executioner's Tool","Blackwing","Cursed Corpse"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Order DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Burst DPS"},
    "Sereniel": {"sets":["Executioner's Tool","Blackwing","Instinctual Growth",
                         "Judgment's Flames","Cursed Corpse"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Instinct DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"60% Crit Rate · Potential 7"},
    "Rin":      {"sets":["Conqueror's Aspect","Orb of Inhibition","Executioner's Tool",
                         "Blackwing","Offering of the Void"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Void DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Void / 1-AP DPS"},
    "Renoa":    {"sets":["Conqueror's Aspect","Executioner's Tool","Blackwing"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Order DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"1-AP card DPS"},
    "Chizuru":  {"sets":["Orb of Inhibition","Executioner's Tool","Seth's Scarab",
                         "Blackwing","Offering of the Void"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Void DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Void Multi-Hit DPS"},
    "Tiphera":  {"sets":["Line of Justice","Tetra's Authority","Executioner's Tool",
                         "Healer's Journey"],
                 "weights":TIPHERA_W,
                 "good_main":{"desire":"Order DMG%",
                              "imagination":["DEF%","Crit Rate%"],
                              "ideal":["Crit Rate%","DEF%"]},
                 "goal":"DEF scaler · 350 DEF"},
    "Hugo":     {"sets":["Executioner's Tool","Blackwing","Line of Justice"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Order DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Follow-up DPS"},
    "Khalipe":  {"sets":["Instinctual Growth","Tetra's Authority","Executioner's Tool"],
                 "weights":KHALIPE_W,
                 "good_main":{"desire":"Instinct DMG%",
                              "imagination":["DEF%","Crit Rate%"],
                              "ideal":["Crit Rate%","DEF%"]},
                 "goal":"300 DEF + Crit · Potential 7"},
    "Orlea":    {"sets":["Glory's Reign","Tetra's Authority","Healer's Journey",
                         "Instinctual Growth"],
                 "weights":DEF_SUP_W,
                 "good_main":{"desire":"HP%",
                              "imagination":["DEF%","HP%"],
                              "ideal":["HP%","DEF%"]},
                 "goal":"300 DEF · Potential 7"},
    "Cassius":  {"sets":["Glory's Reign","Tetra's Authority","Healer's Journey","Seth's Scarab"],
                 "weights":DEF_SUP_W,
                 "good_main":{"desire":"HP%",
                              "imagination":["DEF%","HP%"],
                              "ideal":["HP%","DEF%"]},
                 "goal":"DEF + HP support"},
    "Mika":     {"sets":["Tetra's Authority","Healer's Journey","Seth's Scarab"],
                 "weights":HP_SUP_W,
                 "good_main":{"desire":"HP%",
                              "imagination":["DEF%","HP%"],
                              "ideal":["HP%","DEF%"]},
                 "goal":"Healer / Shield support"},
    "Selena":   {"sets":["Healer's Journey","Tetra's Authority","Seth's Scarab"],
                 "weights":HP_SUP_W,
                 "good_main":{"desire":"HP%",
                              "imagination":["DEF%","HP%"],
                              "ideal":["HP%","DEF%"]},
                 "goal":"Sub-DPS support"},
    "Tressa":   {"sets":["Cursed Corpse","Healer's Journey","Tetra's Authority","Seth's Scarab"],
                 "weights":HP_SUP_W,
                 "good_main":{"desire":"HP%",
                              "imagination":["DEF%","HP%"],
                              "ideal":["HP%","DEF%"]},
                 "goal":"Agony support"},
    "Amir":     {"sets":["Conqueror's Aspect","Tetra's Authority","Executioner's Tool",
                         "Blackwing","Cursed Corpse"],
                 "weights":{"Crit Rate%":0.75,"Crit DMG%":0.75,"DEF":1.0,"DEF%":0.8,
                             "ATK":0.1,"ATK%":0.1,"HP":0.0,"HP%":0.0,"EGO Recovery":0.3,
                             "DoT%":0.0,"Extra DMG%":0.0},
                 "good_main":{"desire":"Void DMG%",
                              "imagination":["DEF%","Crit Rate%"],
                              "ideal":["Crit Rate%","DEF%"]},
                 "goal":"301 DEF · Metalization build"},
    "Diana":    {"sets":["Orb of Inhibition","Conqueror's Aspect","Executioner's Tool",
                         "Blackwing","Offering of the Void"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Void DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Void Discard DPS"},
    "Haru":     {"sets":["Line of Justice","Conqueror's Aspect","Executioner's Tool","Blackwing"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Justice DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Justice Crit DPS"},
    "Kayron":   {"sets":["Offering of the Void","Orb of Inhibition","Cursed Corpse",
                         "Executioner's Tool","Blackwing"],
                 "weights":{"Crit Rate%":0.75,"Crit DMG%":0.75,"DoT%":1.0,"Extra DMG%":0.5,
                             "ATK":0.3,"ATK%":0.3,"DEF":0.0,"DEF%":0.0,"HP":0.0,
                             "HP%":0.0,"EGO Recovery":0.0},
                 "good_main":{"desire":"Void DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Void DoT DPS"},
    "Lucas":    {"sets":["Cursed Corpse","Conqueror's Aspect","Executioner's Tool","Seth's Scarab"],
                 "weights":{"Crit Rate%":0.75,"Crit DMG%":0.75,"DoT%":0.75,"ATK":0.4,
                             "ATK%":0.4,"DEF":0.0,"DEF%":0.0,"HP":0.0,"HP%":0.0,
                             "EGO Recovery":0.0,"Extra DMG%":0.0},
                 "good_main":{"desire":"Order DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Agony sub-DPS"},
    "Luke":     {"sets":["Bullet of Order","Line of Justice","Executioner's Tool","Blackwing"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Order DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Order Bullet DPS"},
    "Magna":    {"sets":["Tetra's Authority","Conqueror's Aspect","Executioner's Tool","Blackwing"],
                 "weights":{"DEF":1.0,"DEF%":0.8,"Crit Rate%":0.6,"Crit DMG%":0.6,
                             "HP":0.2,"HP%":0.2,"ATK":0.0,"ATK%":0.0,"EGO Recovery":0.2,
                             "DoT%":0.0,"Extra DMG%":0.0},
                 "good_main":{"desire":"Void DMG%",
                              "imagination":["DEF%","Crit Rate%"],
                              "ideal":["Crit Rate%","DEF%"]},
                 "goal":"DEF + Crit Counter build"},
    "Maribell": {"sets":["Tetra's Authority","Spark of Passion","Executioner's Tool","Blackwing"],
                 "weights":{"DEF":0.8,"DEF%":0.7,"Crit Rate%":0.7,"Crit DMG%":0.7,
                             "HP":0.1,"HP%":0.1,"ATK":0.1,"ATK%":0.1,"EGO Recovery":0.2,
                             "DoT%":0.0,"Extra DMG%":0.0},
                 "good_main":{"desire":"Passion DMG%",
                              "imagination":["DEF%","Crit Rate%"],
                              "ideal":["Crit Rate%","DEF%"]},
                 "goal":"Shield-scaling DPS"},
    "Mei Lin":  {"sets":["Spark of Passion","Executioner's Tool","Blackwing","Conqueror's Aspect"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Passion DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Passion Upgrade DPS"},
    "Narja":    {"sets":["Tetra's Authority","Healer's Journey","Seth's Scarab"],
                 "weights":HP_SUP_W,
                 "good_main":{"desire":"HP%",
                              "imagination":["DEF%","HP%"],
                              "ideal":["HP%","DEF%"]},
                 "goal":"AP cost reduction support"},
    "Nia":      {"sets":["Healer's Journey","Tetra's Authority","Seth's Scarab"],
                 "weights":HP_SUP_W,
                 "good_main":{"desire":"HP%",
                              "imagination":["DEF%","HP%"],
                              "ideal":["HP%","DEF%"]},
                 "goal":"Draw/Discard engine support"},
    "Owen":     {"sets":["Healer's Journey","Tetra's Authority","Seth's Scarab","Glory's Reign"],
                 "weights":HP_SUP_W,
                 "good_main":{"desire":"HP%",
                              "imagination":["DEF%","HP%"],
                              "ideal":["HP%","DEF%"]},
                 "goal":"Heal support"},
    "Rei":      {"sets":["Offering of the Void","Cursed Corpse","Executioner's Tool",
                         "Seth's Scarab","Healer's Journey"],
                 "weights":{"Crit Rate%":0.6,"Crit DMG%":0.6,"DEF":0.5,"DEF%":0.5,
                             "HP":0.5,"HP%":0.5,"ATK":0.2,"ATK%":0.2,"EGO Recovery":0.4,
                             "DoT%":0.0,"Extra DMG%":0.0},
                 "good_main":{"desire":"Void DMG%",
                              "imagination":["DEF%","Crit Rate%"],
                              "ideal":["Crit Rate%","DEF%"]},
                 "goal":"Morale support / sub-DPS"},
    "Rita":     {"sets":["Instinctual Growth","Judgment's Flames","Executioner's Tool","Blackwing"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Instinct DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Instinct DPS"},
    "Yuki":     {"sets":["Bullet of Order","Line of Justice","Executioner's Tool","Blackwing"],
                 "weights":CRIT_DPS,
                 "good_main":{"desire":"Order DMG%",
                              "imagination":["Crit Rate%","Crit DMG%"],
                              "ideal":["Crit Rate%","Crit DMG%"]},
                 "goal":"Order DPS"},
}

# ── Set lookups ───────────────────────────────────────────────────────────────
SET_TO_CHARS: dict = {}
for _c, _d in CHARS.items():
    for _s in _d["sets"]:
        SET_TO_CHARS.setdefault(_s, []).append(_c)

SET_ALIASES = {
    "spark of passion":"Spark of Passion", "spark":"Spark of Passion",
    "offering of the void":"Offering of the Void", "offering":"Offering of the Void",
    "bullet of order":"Bullet of Order", "bullet":"Bullet of Order",
    "glory's reign":"Glory's Reign", "glory's":"Glory's Reign", "glory":"Glory's Reign",
    "executioner's tool":"Executioner's Tool", "executioner's":"Executioner's Tool", "executioner":"Executioner's Tool",
    "blackwing":"Blackwing", "black wing":"Blackwing",
    "tetra's authority":"Tetra's Authority", "tetra's":"Tetra's Authority", "tetra":"Tetra's Authority",
    "healer's journey":"Healer's Journey", "healer's":"Healer's Journey", "healer":"Healer's Journey",
    "seth's scarab":"Seth's Scarab", "seth's":"Seth's Scarab", "seth":"Seth's Scarab", "scarab":"Seth's Scarab",
    "cursed corpse":"Cursed Corpse", "cursed":"Cursed Corpse", "corpse":"Cursed Corpse",
    "conqueror's aspect":"Conqueror's Aspect", "conqueror's":"Conqueror's Aspect", "conqueror":"Conqueror's Aspect",
    "judgment's flames":"Judgment's Flames", "judgment's":"Judgment's Flames", "judgment":"Judgment's Flames", "flames":"Judgment's Flames",
    "orb of inhibition":"Orb of Inhibition", "orb":"Orb of Inhibition", "inhibition":"Orb of Inhibition",
    "instinctual growth":"Instinctual Growth", "instinctual":"Instinctual Growth", "instinct":"Instinctual Growth",
    "line of justice":"Line of Justice", "line":"Line of Justice", "justice":"Line of Justice",
    "beast's yearning":"Beast's Yearning", "beast's":"Beast's Yearning", "beast":"Beast's Yearning", "yearning":"Beast's Yearning",
}

# ── UI colours ────────────────────────────────────────────────────────────────
COLORS = {
    "bg":"#0d1117",        "border":"#21262d",
    "p1_bg":"#003A8C",     "p1_fg":"#FFD700",
    "p2_bg":"#FFD700",     "p2_fg":"#003A8C",
    "bad_bg":"#1c1c1c",    "bad_fg":"#484848",
    "main_ok_bg":"#0d2d0d","main_ok_fg":"#7ec87e",
    "main_bad_bg":"#2d0d0d","main_bad_fg":"#c87e7e",
    "main_neu_bg":"#1a1a2a","main_neu_fg":"#8888bb",
    "text":"#e6edf3",      "muted":"#7d8590",
    "s":"#FFD700", "a":"#58a6ff", "b":"#7ec87e",
    "c":"#EF9F27", "d":"#c87e7e", "f":"#484848",
}
